### ISSUE TITLE
Null coalescing operator wrongly placed near the ternary operator

### ISSUE THREAD

**Issue by yuchi** [liferay/soy-cheat-sheet#3]
The null coalescing operator `?:` has been placed near the ternary operator `x?y:z` but they are not related at all.

They should be placed in different categories and probably the null coalescing operator should be called «default something» to not intimidate uninitiated :)

**Comment by mthadley** [comment]
Pointing out the equivalent operation using the ternary does help to explain it though:
```
{isNonnull($value) ?  $value : $default}

/* Same as */

{$value ?: $default}
```

**Comment by zenorocha** [comment]
Thanks! What do you think of this https://github.com/liferay/soy-cheat-sheet/commit/f0acbdcce6602ba64905d2b2d9bbb5e49fbfc9cf?

**Comment by yuchi** [comment]
@mthadley is right, but that would deviate from the terseness of the whole document.

I'll tackle it later.
